#pragma once
#include <stdint.h>

//enum class ShaderStage : uint8_t
//{
//	VERTEX_SPECIFICATION,
//	VERTEX_SHADER,
//	TESELLATION_SHADER,
//	GEOMETRY_SHADER,
//	VERTEX_POST_PROCESSING,
//	PRIMITIVE_ASSEMBLY,
//	RASTERIZATION,
//	FRAGMENT_SHADER,
//	PER_SAMPLE_OPERATIONS,
//	END
//};